spring:
  kafka:
    bootstrap-servers: {kafka-server}
  cloud:
    gateway:
      routes:
        - id: open-service
          uri: lb://backend-service
          predicates:
            - Path=/open/**

        - id: backend-route
          uri: lb://backend-service
          predicates:
            - Path=/**
          filters:
            - name: CustomAuthFilter
              args:
                headerName: Authorization
                granted: Bearer
    loadbalancer:
      configurations: health-check
    discovery:
      client:
        simple:
          instances:
            backend-service:
              - secure: false
                port: 80
                host: address_be1
                serviceId: backend-service
                instanceId: backend-service-1
              - secure: false
                port: 80
                host: address_be2
                serviceId: backend-service
                instanceId: backend-service-2

server:
  port: 8080
logging:
  level:
    com : DEBUG

kafka:
  topic:
    log: GatewayAPI

jwt:
  secret: jwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecret
